### ISSUE TITLE
Zollern galaxy map issue

### ISSUE THREAD

**Issue by SpaceTrooper98** [alphawolf918/Zollern-Galaxy#62]
When I zoom in on a planet, the veiw goes to somewhere way off and I can't access the space stations I built for each planet in this mod. I don't know if it a confliction with the AsmodeusCore map from galaxy space. I noticed the note on the page mentioning a similar issue I'm dealing with but the download link is showing version 2.0.29 and not 2.0.8.

**Comment by alphawolf918** [comment]
It's a bug with Galacticraft. Make sure you don't have any of the Z coordinates for any of the planets.

**Comment by SpaceTrooper98** [comment]
How do I change the y coordinates for the planets?

**Comment by alphawolf918** [comment]
The config file lets you change the X, Y and Z coordinates of each star system, and I could have sworn that it let you change it for the planets, but as I'm looking just now, I don't actually see that. So that's something I can add in the future. If you're using MJRLegends' space map, it _might_ work better, but I'm not all that familiar with GalaxySpace. A different map would cause the issue, though, yes. I didn't even know AsmodeousCore added a new map version.

So it's all probably the same issue from 0.8, really. I would pass this on to the GC devs and see what they say. If they have a quick fix for me to do, I'll apply it in the next update, but ultimately I believe it's a combination of mods not behaving together.
