### ISSUE TITLE
Metztli Issues or Noticeables

### ISSUE THREAD

**Issue by xDawnshadow** [alphawolf918/Zollern-Galaxy#66]
Here are some things which felt either odd to me or may be a bug

![2021-11-27_13 22 04](https://user-images.githubusercontent.com/67586937/143766534-835cea5e-5c18-445c-8b04-9861564247f3.png)
Very high Spawnrate of the species living there

![2021-11-27_13 33 28](https://user-images.githubusercontent.com/67586937/143766552-38185b8f-a426-4d06-ab05-be25f7e63ce2.png)
The trees are mostly mushrooms, some are half in half, could be that is supposed to be like this, but it felt off to me

![2021-11-27_13 35 15](https://user-images.githubusercontent.com/67586937/143766601-544e50fd-3c25-4aa6-b278-267c55af80fc.png)
![2021-11-27_13 35 47](https://user-images.githubusercontent.com/67586937/143766606-6c28ed5a-128c-49bc-8f88-c1b3fb0efc72.png)
![2021-11-27_13 36 07](https://user-images.githubusercontent.com/67586937/143766631-7a2dd018-4a15-462e-9dd5-9558a6ff9657.png)
The Mobs still had its Names/Nametags on it, I am pretty sure this shouldn't be like that.

**Comment by alphawolf918** [comment]
Name tags are supposed to show for Mutant Zombies, but I can set that as a config option, too. The mushroom trees and the regular trees doing a mash-up thing is indeed a bug, yeah. Haven't found the fix to that yet, but it's something I've been looking into. Need to put it on my Trello board, so I can remember it, thanks for the reminder. The high spawn-rate of the villagers that live there is something I'm currently working on. For now, if it's causing too much trouble, you can turn off their spawning in the config. That way, they only still spawn in the villages instead of everywhere else.

Again, thank you so much for bringing all of this to my attention. I'll leave all three of these issues up until I get most of them taken care of. Keep in mind that it may not be all at once, but these are things I plan to get to. You put in a lot of time and effort to show me these, provided screenshots, reference points, and were constructive and respectful about it. I appreciate that very much.

**Comment by alphawolf918** [comment]
So I haven't _solved_ all of this yet, but I have got it up on my Trello board. For now, I'm going to close this. I plan to look more into it, though. Thanks again.
