### ISSUE TITLE
Vortex Issues or Noticeables

### ISSUE THREAD

**Issue by xDawnshadow** [alphawolf918/Zollern-Galaxy#67]
![2021-11-27_13 41 29](https://user-images.githubusercontent.com/67586937/143766683-e5a15026-97d9-449d-aa98-a7c0361f5fab.png)
The Generation of these "Pods" I'll call them, is often in the air 

![2021-11-27_13 42 46](https://user-images.githubusercontent.com/67586937/143766730-a8d6fb4d-4104-45f4-90ce-5f7ca8e444da.png)
The Purple Creepers are missing some textures on the Back as well at their feet

![2021-11-27_13 43 00](https://user-images.githubusercontent.com/67586937/143766779-5fc9f224-c85c-4f21-9599-6d911a6e4a79.png)
Alien Villagers keep spawning on different planets randomly in the landscape without a Village nearby

Some other noticeables were : 
- Very Harsh FPS Spikes
- Resulting in "Porting around" or the Planet is "moving", I am unsure
- Thunder Cracks can still be heard in the celestial Screen when you start your rocket and lift off
The first two are probably results of the lava Seas/Oceans there in combination with the rain there; the ambience is very likeable, but it should be considered that lava oceans are heavily influencing performance

**Comment by alphawolf918** [comment]
Vortex basically needs a full rewrite, yeah. The thing I didn't know was that the Mega Creepers were hurting for textures, thanks for letting me know about that. The planet [Vortex] isn't moving; it's the "wind blowing" event pushing the Player around. Two options are 1.) You can disable this in the config or 2.) You can craft a "Storm Amulet" and that will prevent it from firing, e.g. the wind will not blow you around anymore. The lightning noise in the background is client-side only, so that's why you hear it when still in the rocket screen thing (because server-side, the Player hasn't actually traveled anywhere and is in a holding pattern).

I might do away with the lava ocean, yeah. For reference though, at least for me, the heavy TPS spikes are still there even when _not_ in one of those biomes, unfortunately. It's something I plan to get to.

The pods (called "Outposts") are not supposed to generate in the air, no. They also are not meant to spawn in ocean-like biomes, and that's one of the things on my Trello board that I plan to fix. For now, you can set their generation rate to 0 in the config, if you like.

Thank you for letting me know about these. I'll leave this open until I get most of it squared away.

**Comment by alphawolf918** [comment]
This one I'm still leaving up, because Vortex itself is just highly problematic.

**Comment by alphawolf918** [comment]
Alrighty! So most of this _should_ be fixed - or at least mitigated - in the next update. I'm introducing some new config options, fixed a few issues, reduced some values, etc. so that it's not _as_ heavy on resources. Might need to temper it more, but I want to see how Player interaction goes first. Thanks again for this, tons. You're the best; keep being awesome!
