### ISSUE TITLE
The temperature value changed from the last update.

### ISSUE THREAD

**Issue by Kydhead** [alphawolf918/Zollern-Galaxy#70]
I did check my last issue and I will say that yes the equation does work and that I was probably basing it off of memory, BUT I still realized something was off, in the last version, aka image 1, the temperature value was different from the current version aka image 2. I don't know if this change was on purpose or if it was an accident, and I hope I didn't cause an inconvenience in the last one.
![2021-12-04_16 34 28](https://user-images.githubusercontent.com/95550007/144726638-a4340de9-1206-4dd3-b218-8bb678cafbaf.pn
![2021-12-04_16 29 57](https://user-images.githubusercontent.com/95550007/144726648-567fdac6-64bb-45d1-a93a-f57e556dcacb.png)
g)

**Comment by Kydhead** [comment]
![2021-12-04_16 34 28](https://user-images.githubusercontent.com/95550007/144726685-58463939-b3b7-4370-a07b-9603514c6026.png)

image 2 did not appear, I got it backwards, image 1 is the new version and this image is the old version

**Comment by alphawolf918** [comment]
I will post here what I did on my Discord server for this mod:

For anyone curious, there is a small AESTHETIC glitch with the Galactic HUD. The formula works just fine, but for some reason there is a dash (-) in front of the temperature. I'll be looking into it. Verified that -93 is in fact -70. They're just not supposed to be negative. Also, keep in mind: temps are *rounded*. So it won't be 110% accurate. That's all though, just has a dash there for some reason. Probably a string concatenation glitch or something.

**NOTE**: This DOES NOT affect gameplay! It's purely for display only, and only shows when holding the HUD. So if it's really a bother, then it's best to avoid the HUD for now. I'm taking a break on working on it too much since it's the holidays. Thanks everyone.

**Comment by alphawolf918** [comment]
This is not as big of an issue as you consistently are making it out to be: first on the GC forums, then once on here (both rudely), and then on here a second time. Although, this time you were actually respectful about it, provided screenshots and corrected yourself before making an assumption, which I appreciate. It's on my radar, but it probably won't be soon. Thanks for letting me know.

**Comment by alphawolf918** [comment]
This has been fixed and will be in the next release.
