### ISSUE TITLE
Crash game

### ISSUE THREAD

**Issue by Mornikale1** [alphawolf918/Zollern-Galaxy#85]
minecraft crashes when I get into a rocket and take off, at 14 seconds of the countdown, microfreeze, and minecraft crashes. (solo game)

I was waiting for the new version to find out what's new added

Minecraft 1.12.2
mod version: 2.0.40
Ram Allocated: 4gb
[crash-2022-02-22_21.44.09-server.txt](https://github.com/alphawolf918/Zollern-Galaxy/files/8119399/crash-2022-02-22_21.44.09-server.txt)

**Comment by alphawolf918** [comment]
Hi there,

Try enabling chest validation in the config, and please make sure that you are using the latest version.

I will take a more in depth look at this when I get home.

**Comment by Mornikale1** [comment]
ok i will check chests, later write about this

**Comment by alphawolf918** [comment]
I will look into this, but please don't try telling me what to do. I'm going to get to this in my own time. Thank you.

**Comment by Mornikale1** [comment]
ok

**Comment by alphawolf918** [comment]
Hi,

Please try the latest version. It also includes a config option now where you can disable Altum treasure chest generation (since that's what was causing your game to crash, but I can't seem to reproduce that specific issue). In any case, the actual cause of the crash has been addressed and fixed.

I'll leave this open for a couple of days, and if I don't hear anything in that time frame, then I'll just close the ticket. You only need to reply if this doesn't work. Thanks for letting me know about it.

**Comment by Mornikale1** [comment]
Yes, please, everything works fine now) thank you
You can close the ticket
